name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath
          coverage: none

      - name: Composer Install
        run: composer install --no-interaction

      - name: Generate Transfer
        run: APPLICATION_ENV=DE vendor/bin/console transfer:generate

  code-sniffer:
    name: code-sniffer
    needs: build
    steps:
      - name: Code Sniffer
        run: composer phpcs

  phpstan:
    name: phpstan
    needs: build
    steps:
      - name: PHPStan
        run: composer phpstan

  phplint:
    name: phplint
    needs: build
    steps:
      - name: PHPLint
        run: composer phplint


